var searchData=
[
  ['xcellaugmentedfeedback',['XCellAugmentedFeedback',['../group___x_c_e_l_l___a_u_g_m_e_n_t_e_d___f_e_e_d_b_a_c_k.html',1,'']]],
  ['xcell_20binding_20layer',['XCell Binding Layer',['../group___x_c_e_l_l___b_i_n_d_i_n_g___l_a_y_e_r.html',1,'']]],
  ['xcellbusinessrulesbindinglayer',['XCellBusinessRulesBindingLayer',['../group___x_c_e_l_l___b_u_s_i_n_e_s_s___r_u_l_e_s___b_i_n_d_i_n_g___l_a_y_e_r.html',1,'']]],
  ['xcellbusinessrulesbindinglayer',['XCellBusinessRulesBindingLayer',['../group___x_c_e_l_l___b_u_s_i_n_e_s_s___r_u_l_e_s___b_i_n_d_i_n_g___l_a_y_e_r___g_r_o_u_p.html',1,'']]],
  ['xcellbusinessrulescutevent',['XCellBusinessRulesCutEvent',['../group___x_c_e_l_l___b_u_s_i_n_e_s_s___r_u_l_e_s___c_u_t___e_v_e_n_t.html',1,'']]],
  ['xcellbusinessrulesdirectoryentry',['XCellBusinessRulesDirectoryEntry',['../group___x_c_e_l_l___b_u_s_i_n_e_s_s___r_u_l_e_s___d_i_r_e_c_t_o_r_y___e_n_t_r_y.html',1,'']]],
  ['xcellbusinessrulesendevent',['XCellBusinessRulesEndEvent',['../group___x_c_e_l_l___b_u_s_i_n_e_s_s___r_u_l_e_s___e_n_d___e_v_e_n_t.html',1,'']]],
  ['xcellbusinessrulesevents',['XCellBusinessRulesEvents',['../group___x_c_e_l_l___b_u_s_i_n_e_s_s___r_u_l_e_s___e_v_e_n_t_s___g_r_o_u_p.html',1,'']]],
  ['xcellbusinessrulesheartrateevent',['XCellBusinessRulesHeartRateEvent',['../group___x_c_e_l_l___b_u_s_i_n_e_s_s___r_u_l_e_s___h_e_a_r_t_r_a_t_e___e_v_e_n_t.html',1,'']]],
  ['xcellbusinessruleshustleevent',['XCellBusinessRulesHustleEvent',['../group___x_c_e_l_l___b_u_s_i_n_e_s_s___r_u_l_e_s___h_u_s_t_l_e___e_v_e_n_t.html',1,'']]],
  ['xcellbusinessrulesjumpevent',['XCellBusinessRulesJumpEvent',['../group___x_c_e_l_l___b_u_s_i_n_e_s_s___r_u_l_e_s___j_u_m_p___e_v_e_n_t.html',1,'']]],
  ['xcellbusinessrulespressevent',['XCellBusinessRulesPressEvent',['../group___x_c_e_l_l___b_u_s_i_n_e_s_s___r_u_l_e_s___p_r_e_s_s___e_v_e_n_t.html',1,'']]],
  ['xcellbusinessrulesreactionevent',['XCellBusinessRulesReactionEvent',['../group___x_c_e_l_l___b_u_s_i_n_e_s_s___r_u_l_e_s___r_e_a_c_t_i_o_n___e_v_e_n_t.html',1,'']]],
  ['xcellbusinessrulessession',['XCellBusinessRulesSession',['../group___x_c_e_l_l___b_u_s_i_n_e_s_s___r_u_l_e_s___s_e_s_s_i_o_n.html',1,'']]],
  ['xcellbusinessrulesshuttleevent',['XCellBusinessRulesShuttleEvent',['../group___x_c_e_l_l___b_u_s_i_n_e_s_s___r_u_l_e_s___s_h_u_t_t_l_e___e_v_e_n_t.html',1,'']]],
  ['xcellbusinessrulessprintevent',['XCellBusinessRulesSprintEvent',['../group___x_c_e_l_l___b_u_s_i_n_e_s_s___r_u_l_e_s___s_p_r_i_n_t___e_v_e_n_t.html',1,'']]],
  ['xcellbusinessrulesstartevent',['XCellBusinessRulesStartEvent',['../group___x_c_e_l_l___b_u_s_i_n_e_s_s___r_u_l_e_s___s_t_a_r_t___e_v_e_n_t.html',1,'']]],
  ['xcellbytearray',['XCellByteArray',['../group___x_c_e_l_l___b_y_t_e___a_r_r_a_y___c___c_l_a_s_s.html',1,'']]],
  ['xcellbyteconversionutils',['XCellByteConversionUtils',['../group___x_c_e_l_l___b_y_t_e___c_o_n_v_e_r_s_i_o_n___u_t_i_l_s.html',1,'']]],
  ['xcell_20c_20modules',['XCell C Modules',['../group___x_c_e_l_l___c___m_o_d_u_l_e_s.html',1,'']]],
  ['xcell_20device',['XCell Device',['../group___x_c_e_l_l___d_e_v_i_c_e.html',1,'']]],
  ['xcelldevicestatus',['XCellDeviceStatus',['../group___x_c_e_l_l___d_e_v_i_c_e___s_t_a_t_u_s___c_l_a_s_s.html',1,'']]],
  ['xcelldownloadsessions',['XCellDownloadSessions',['../group___x_c_e_l_l___d_o_w_n_l_o_a_d___s_e_s_s_i_o_n_s___m_o_d_u_l_e.html',1,'']]],
  ['xcellheartrate',['XCellHeartRate',['../group___x_c_e_l_l___h_e_a_r_t_r_a_t_e___m_o_d_u_l_e.html',1,'']]],
  ['xcellposition',['XCellPosition',['../group___x_c_e_l_l___p_o_s_i_t_i_o_n___m_o_d_u_l_e.html',1,'']]],
  ['xcellrequestqueue',['XCellRequestQueue',['../group___x_c_e_l_l___r_e_q_u_e_s_t___q_u_e_u_e___c_l_a_s_s.html',1,'']]],
  ['xcellrequestqueuemanager',['XCellRequestQueueManager',['../group___x_c_e_l_l___r_e_q_u_e_s_t___q_u_e_u_e___m_a_n_a_g_e_r___c_l_a_s_s.html',1,'']]],
  ['xcellsensor',['XCellSensor',['../group___x_c_e_l_l___s_e_n_s_o_r___c_l_a_s_s.html',1,'']]],
  ['xcelltime',['XCellTime',['../group___x_c_e_l_l___t_i_m_e___m_o_d_u_l_e.html',1,'']]]
];
